ben_users_public:
    pattern:  /public/{perPage}
    defaults: { _controller: BenUserBundle:Admin:public, perPage: 10}

ben_users:
    pattern:  /adherants
    defaults: { _controller: BenUserBundle:Admin:index }

ben_users_ajax:
    pattern:  /userslist
    defaults: { _controller: BenUserBundle:Admin:ajaxList }
    requirements: { _method: post }

ben_archive:
    pattern:  /archive
    defaults: { _controller: BenUserBundle:Admin:archive }

ben_archive_set:
    pattern:  /archive/set/{stat}
    defaults: { _controller: BenUserBundle:Admin:setArchive }
    requirements: { _method: post }

ben_show_user:
    pattern:  /show/{id}
    defaults: { _controller: BenUserBundle:Admin:show }

ben_new_user:
    pattern:  /new
    defaults: { _controller: BenUserBundle:Admin:new }

ben_add_user:
    pattern:  /add
    defaults: { _controller: BenUserBundle:Admin:add }
    requirements: { _method: post }

ben_edit_user:
    pattern:  /edit/{id}
    defaults: { _controller: BenUserBundle:Admin:edit }

ben_update_user:
    pattern:  /update/{id}
    defaults: { _controller: BenUserBundle:Admin:update }
    requirements: { _method: post }

ben_enable_users:
    pattern:  /users/active/{etat}
    defaults: { _controller: "BenUserBundle:Admin:enableUsers" , etat: 1}
    requirements: { _method: post }

ben_promote_users:
    pattern:  /promote/{role}
    defaults: { _controller: "BenUserBundle:Admin:setRole" , role: user}
    requirements: { _method: post }

ben_delete_user:
    pattern:  /{id}/delete
    defaults: { _controller: "BenUserBundle:Admin:delete" }
    requirements: { _method: post }

ben_remove_users:
    pattern:  /delete
    defaults: { _controller: "BenUserBundle:Admin:removeUsers" }
    requirements: { _method: post }

ben_users_export:
    pattern:  /csv
    defaults: { _controller: "BenUserBundle:Admin:toCsv" }

ben_profile_edit:
    pattern:  /me/edit/{name}
    defaults: { _controller: "BenUserBundle:Admin:editMe" }

ben_profile_update:
    pattern:  /me/{id}/update
    defaults: { _controller: "BenUserBundle:Admin:updateMe" }
    requirements: { _method: post }

ben_pdf:
    pattern:  /pdf/{users}
    defaults: { _controller: "BenUserBundle:Admin:toPdf"}

ben_export_xml:
    pattern:  /xml
    defaults: { _controller: "BenUserBundle:Admin:toXml"}

ben_export_excel:
    pattern:  /excel
    defaults: { _controller: "BenUserBundle:Admin:toExcel"}

ben_badge_user:
    pattern:  /badge/{users}
    defaults: { _controller: "BenUserBundle:Admin:showBadge" }

ben_ticket_user:
    pattern:  /printTicket/{users}
    defaults: { _controller: "BenUserBundle:Admin:printTicket" }

add_users_log:
    pattern:  /log
    defaults: { _controller: BenUserBundle:Admin:log }
    requirements: { _method: post }

ben_mail:
    pattern:  /mail
    defaults: { _controller: BenUserBundle:Admin:sendMail }
    requirements: { _method: post }

ben_mail_alert:
    pattern:  /{id}/alert/mail
    defaults: { _controller: BenUserBundle:Admin:alertMail }

ben_print_alert:
    pattern:  /{id}/alert/print
    defaults: { _controller: BenUserBundle:Admin:alertPrint }

ben_clear_log:
    pattern:  /log/clear/{id}/{user}
    defaults: { _controller: BenUserBundle:Admin:clearLog, id: 0, user: 0 }