imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@BenUserBundle/Resources/config/config.yml" }
    - { resource: "@BenUserBundle/Resources/config/services.yml" }
    - { resource: "@BenMessageBundle/Resources/config/config.yml" }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    form:
        resources:
            - 'BenAssociationBundle:Form:fields.html.twig'
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [BenAssociationBundle, FOSMessageBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                charset:  UTF8
                driver:   %database_driver%
                host:     %database_host%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        dql:
            datetime_functions:
                DATEDIFF: Ben\UserBundle\DQL\DateDiff 
                Cast: Ben\UserBundle\DQL\Cast 

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    # host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    # spool:
    #     type: file
    #     path: "%kernel.root_dir%/swiftmailer/spool"
    logging: "%kernel.debug%"

#knp_snappy pdf bundle
knp_snappy:
    pdf:
        enabled:    true
        binary:     C:/wkhtmltopdf/bin/wkhtmltopdf.exe
        options:    []