ben_association:
    resource: "@BenAssociationBundle/Resources/config/routing.yml"
    prefix:   /
ben_user:
    resource: "@BenUserBundle/Resources/config/routing.yml"
    prefix:   /
fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.yml"
    prefix: /messages