#fos userbundle
fos_user:
    db_driver:     orm
    firewall_name: main
    user_class: Ben\UserBundle\Entity\User
    group:
        group_class: Ben\UserBundle\Entity\Group
        form:          
            type: ben_user_group
    from_email:
        address:        info@knowledge.com
        sender_name:    admin
    registration:
        confirmation:
            enabled:    true