#fos
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password     
fos_autocomplete:
    pattern:   /users/autocomplete
    defaults:  { _controller: BenUserBundle:User:autocomplete }


#admin section
ben_user_profile:
    resource: "@BenUserBundle/Resources/config/routing/manager.yml"
    prefix: /

#Groups
ben_user_group:
    resource: "@BenUserBundle/Resources/config/routing/group.yml"
    prefix: /group

fos_user_security_login:
    pattern:   /
    defaults:  { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    pattern:   /login_check
    defaults:  { _controller: FOSUserBundle:Security:check }

fos_user_security_logout:
    pattern:   /logout
    defaults:  { _controller: FOSUserBundle:Security:logout }